## Kira Tahmin Modeli

In [4]:
import os as os #os modulu dosya ve dizinler ile ilgili işlemler
import numpy as np
import pandas as pd

In [5]:
def drop_columns(df,cols):
    """
    This function removes the columns from a DataFrame.
    """
    for col in cols:
        try:
            df.drop(col,axis=1,inplace=True)
        except Exception as e:
            print(f"Bir hata oluştu : {e}")

yorum satırları arasına yazdıgımız fonksiyonun dokumantasyonunu yazabiliriz help() ile bu dokumantasyonu gorebiliriz.

In [6]:
help(drop_columns)

Help on function drop_columns in module __main__:

drop_columns(df, cols)
    This function removes the columns from a DataFrame.

In [7]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annotations',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'col',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'from_dummies',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_hdf',
 'read_html',
 'read_iceberg',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'wide_to_long']

dir() ile paket icerisinde gelenleri gorebiliriz

'ArrowDtype' --> A ve D buyuk bu bir sınıf(class)
'read_csv' --> kucuk harflerle yazılmıs ve alt cizgi ile ayrılmıs olanlar fonksiyonlar

In [8]:
help(pd.read_csv)

Help on function read_csv in module pandas:

read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    *,
    sep: 'str | None | lib.NoDefault' = <no_default>,
    delimiter: 'str | None | lib.NoDefault' = None,
    header: "int | Sequence[int] | None | Literal['infer']" = 'infer',
    names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>,
    index_col: 'IndexLabel | Literal[False] | None' = None,
    usecols: 'UsecolsArgType' = None,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters: 'Mapping[HashableT, Callable] | None' = None,
    true_values: 'list | None' = None,
    false_values: 'list | None' = None,
    skipinitialspace: 'bool' = False,
    skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None,
    skipfooter: 'int' = 0,
    nrows: 'int | None' = None,
    na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None,
    keep_default_na: 'bool' = True,
    na_filter: 'bool' = True,
    skip_blank_lines: 'bool' = True,
    parse_dates: 'bool | Sequence[Hashable] | None' = None,
    date_format: 'str | dict[Hashable, str] | None' = None,
    dayfirst: 'bool' = False,
    cache_dates: 'bool' = True,
    iterator: 'bool' = False,
    chunksize: 'int | None' = None,
    compression: 'CompressionOptions' = 'infer',
    thousands: 'str | None' = None,
    decimal: 'str' = '.',
    lineterminator: 'str | None' = None,
    quotechar: 'str' = '"',
    quoting: 'int' = 0,
    doublequote: 'bool' = True,
    escapechar: 'str | None' = None,
    comment: 'str | None' = None,
    encoding: 'str | None' = None,
    encoding_errors: 'str | None' = 'strict',
    dialect: 'str | csv.Dialect | None' = None,
    on_bad_lines: 'str' = 'error',
    low_memory: 'bool' = True,
    memory_map: 'bool' = False,
    float_precision: "Literal['high', 'legacy', 'round_trip'] | None" = None,
    storage_options: 'StorageOptions | None' = None,
    dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>
) -> 'DataFrame | TextFileReader'
    Read a comma-separated values (csv) file into DataFrame.

    Also supports optionally iterating or breaking of the file
    into chunks.

    Additional help can be found in the online docs for
    `IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

    Parameters
    ----------
    filepath_or_buffer : str, path object or file-like object
        Any valid string path is acceptable. The string could be a URL. Valid
        URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
        expected. A local file could be: file://localhost/path/to/table.csv.

        If you want to pass in a path object, pandas accepts any ``os.PathLike``.

        By file-like object, we refer to objects with a ``read()`` method, such as
        a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
    sep : str, default ','
        Character or regex pattern to treat as the delimiter. If ``sep=None``, the
        C engine cannot automatically detect
        the separator, but the Python parsing engine can, meaning the latter will
        be used and automatically detect the separator from only the first valid
        row of the file by Python's builtin sniffer tool, ``csv.Sniffer``.
        In addition, separators longer than 1 character and different from
        ``'\s+'`` will be interpreted as regular expressions and will also force
        the use of the Python parsing engine. Note that regex delimiters are prone
        to ignoring quoted data. Regex example: ``'\r\t'``.
    delimiter : str, optional
        Alias for ``sep``.
    header : int, Sequence of int, 'infer' or None, default 'infer'
        Row number(s) containing column labels and marking the start of the
        data (zero-indexed). Default behavior is to infer the column names:
        if no ``names``
        are passed the behavior is identical to ``header=0`` and column
        names are inferred from the first line of the file, if column
        names are passed explicitly to ``names`` then the behavior is identical to
        ``header=None``. Explicitly pass ``header=0`` to be able to
        replace existing names. The header can be a list of integers that
        specify row locations for a :class:`~pandas.MultiIndex` on the columns
        e.g. ``[0, 1, 3]``. Intervening rows that are not specified will be
        skipped (e.g. 2 in this example is skipped). Note that this
        parameter ignores commented lines and empty lines if
        ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
        data rather than the first line of the file.

        When inferred from the file contents, headers are kept distinct from
        each other by renaming duplicate names with a numeric suffix of the form
        ``".{{count}}"`` starting from 1, e.g. ``"foo"`` and ``"foo.1"``.
        Empty headers are named ``"Unnamed: {{i}}"`` or ``
        "Unnamed: {{i}}_level_{{level}}"``
        in the case of MultiIndex columns.
    names : Sequence of Hashable, optional
        Sequence of column labels to apply. If the file contains a header row,
        then you should explicitly pass ``header=0`` to override the column names.
        Duplicates in this list are not allowed.
    index_col : Hashable, Sequence of Hashable or False, optional
        Column(s) to use as row label(s), denoted either by column labels or column
        indices.  If a sequence of labels or indices is given,
        :class:`~pandas.MultiIndex`
        will be formed for the row labels.

        Note: ``index_col=False`` can be used to force pandas to *not* use the first
        column as the index, e.g., when you have a malformed file with delimiters at
        the end of each line.
    usecols : Sequence of Hashable or Callable, optional
        Subset of columns to select, denoted either
        by column labels or column indices.
        If list-like, all elements must either
        be positional (i.e. integer indices into the document columns) or strings
        that correspond to column names provided either by the user in ``names`` or
        inferred from the document header row(s).
        If ``names`` are given, the document
        header row(s) are not taken into account. For example, a valid list-like
        ``usecols`` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
        Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
        To instantiate a :class:`~pandas.DataFrame` from ``data`` with element order
        preserved use ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]``
        for columns in ``['foo', 'bar']`` order or
        ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
        for ``['bar', 'foo']`` order.

        If callable, the callable function will be evaluated against the column
        names, returning names where the callable function evaluates to ``True``. An
        example of a valid callable argument would be ``lambda x: x.upper() in
        ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
        parsing time and lower memory usage.
    dtype : dtype or dict of {{Hashable : dtype}}, optional
        Data type(s) to apply to either the whole dataset or individual columns.
        E.g., ``{{'a': np.float64, 'b': np.int32, 'c': 'Int64'}}``
        Use ``str`` or ``object`` together with suitable ``na_values`` settings
        to preserve and not interpret ``dtype``.
        If ``converters`` are specified, they will be applied INSTEAD
        of ``dtype`` conversion. Specify a ``defaultdict`` as input where
        the default determines the ``dtype``
        of the columns which are not explicitly
        listed.
    engine : {{'c', 'python', 'pyarrow'}}, optional
        Parser engine to use. The C and pyarrow engines are faster,
        while the python engine
        is currently more feature-complete. Multithreading
        is currently only supported by
        the pyarrow engine. Some features of the "pyarrow" engine
        are unsupported or may not work correctly.
    converters : dict of {{Hashable : Callable}}, optional
        Functions for converting values in specified columns. Keys can either
        be column labels or column indices.
    true_values : list, optional
        Values to consider as ``True`` in addition
        to case-insensitive variants of 'True'.
    false_values : list, optional
        Values to consider as ``False`` in addition to case-insensitive
        variants of 'False'.
    skipinitialspace : bool, default False
        Skip spaces after delimiter.
    skiprows : int, list of int or Callable, optional
        Line numbers to skip (0-indexed) or number of lines to skip (``int``)
        at the start of the file.

        If callable, the callable function will be evaluated against the row
        indices, returning ``True`` if the row should be skipped and ``False``
        otherwise.
        An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
    skipfooter : int, default 0
        Number of lines at bottom of file to skip (Unsupported with ``engine='c'``).
    nrows : int, optional
        Number of rows of file to read. Useful for reading pieces of large files.
        Refers to the number of data rows in the returned DataFrame, excluding:

        * The header row containing column names.
        * Rows before the header row, if ``header=1`` or larger.

        Example usage:

        * To read the first 999,999 (non-header) rows:
          ``read_csv(..., nrows=999999)``

        * To read rows 1,000,000 through 1,999,999:
          ``read_csv(..., skiprows=1000000, nrows=999999)``

    na_values : Hashable, Iterable of Hashable or dict of {{Hashable : Iterable}},
        optional
        Additional strings to recognize as ``NA``/``NaN``. If ``dict``
        passed, specific
        per-column ``NA`` values.  By default the following values
        are interpreted as
        ``NaN``: empty string, "NaN", "N/A", "NULL", and other common
        representations of missing data.
    keep_default_na : bool, default True
        Whether or not to include the default ``NaN`` values when parsing the data.
        Depending on whether ``na_values`` is passed in, the behavior is as follows:

        * If ``keep_default_na`` is ``True``, and ``na_values``
          are specified, ``na_values``
          is appended to the default ``NaN`` values used for parsing.
        * If ``keep_default_na`` is ``True``, and ``na_values`` are not specified, only
          the default ``NaN`` values are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are specified, only
          the ``NaN`` values specified ``na_values`` are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are not specified, no
          strings will be parsed as ``NaN``.

        Note that if ``na_filter`` is passed in as ``False``,
        the ``keep_default_na`` and
        ``na_values`` parameters will be ignored.
    na_filter : bool, default True
        Detect missing value markers (empty strings and the value of ``na_values``). In
        data without any ``NA`` values, passing ``na_filter=False`` can improve the
        performance of reading a large file.
    skip_blank_lines : bool, default True
        If ``True``, skip over blank lines rather than interpreting as ``NaN`` values.
    parse_dates : bool, None, list of Hashable, default None
        The behavior is as follows:

        * ``bool``. If ``True`` -> try parsing the index.
        * ``None``. Behaves like ``True`` if ``date_format`` is specified.
        * ``list`` of ``int`` or names.
          e.g. If ``[1, 2, 3]`` -> try parsing columns 1, 2, 3
          each as a separate date column.

        If a column or index cannot be represented as an array of ``datetime``,
        say because of an unparsable value or a mixture of timezones, the column
        or index will be returned unaltered as an ``object`` data type. For
        non-standard ``datetime`` parsing, use :func:`~pandas.to_datetime` after
        :func:`~pandas.read_csv`.

        Note: A fast-path exists for iso8601-formatted dates.
    date_format : str or dict of column -> format, optional
        Format to use for parsing dates and/or times when
        used in conjunction with ``parse_dates``.
        The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
        `strftime documentation
        <https://docs.python.org/3/library/datetime.html
        #strftime-and-strptime-behavior>`_ for more information on choices, though
        note that :const:`"%f"`` will parse all the way up to nanoseconds.
        You can also pass:

        - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
          time string (not necessarily in exactly the same format);
        - "mixed", to infer the format for each element individually. This is risky,
          and you should probably use it along with `dayfirst`.

        .. versionadded:: 2.0.0
    dayfirst : bool, default False
        DD/MM format dates, international and European format.
    cache_dates : bool, default True
        If ``True``, use a cache of unique, converted dates to apply the ``datetime``
        conversion. May produce significant speed-up when parsing duplicate
        date strings, especially ones with timezone offsets.

    iterator : bool, default False
        Return ``TextFileReader`` object for iteration or getting chunks with
        ``get_chunk()``.
    chunksize : int, optional
        Number of lines to read from the file per chunk. Passing a value will cause the
        function to return a ``TextFileReader`` object for iteration.
        See the `IO Tools docs
        <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
        for more information on ``iterator`` and ``chunksize``.

    compression : str or dict, default 'infer'
        For on-the-fly decompression of on-disk data.
        If 'infer' and 'filepath_or_buffer' is
        path-like, then detect compression from the following extensions: '.gz',
        '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
        (otherwise no compression).
        If using 'zip' or 'tar', the ZIP file must contain only
        one data file to be read in.
        Set to ``None`` for no decompression.
        Can also be a dict with key ``'method'`` set
        to one of {``'zip'``, ``'gzip'``, ``'bz2'``,
        ``'zstd'``, ``'xz'``, ``'tar'``} and
        other key-value pairs are forwarded to
        ``zipfile.ZipFile``, ``gzip.GzipFile``,
        ``bz2.BZ2File``, ``zstandard.ZstdDecompressor``, ``lzma.LZMAFile`` or
        ``tarfile.TarFile``, respectively.
        As an example, the following could be passed for
        Zstandard decompression using a
        custom compression dictionary:
        ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

    thousands : str (length 1), optional
        Character acting as the thousands separator in numerical values.
    decimal : str (length 1), default '.'
        Character to recognize as decimal point (e.g., use ',' for European data).
    lineterminator : str (length 1), optional
        Character used to denote a line break. Only valid with C parser.
    quotechar : str (length 1), optional
        Character used to denote the start and end of a quoted item. Quoted
        items can include the ``delimiter`` and it will be ignored.
    quoting : {{0 or csv.QUOTE_MINIMAL, 1 or csv.QUOTE_ALL,
        2 or csv.QUOTE_NONNUMERIC, 3 or csv.QUOTE_NONE}}, default csv.QUOTE_MINIMAL
        Control field quoting behavior per ``csv.QUOTE_*`` constants. Default is
        ``csv.QUOTE_MINIMAL`` (i.e., 0) which implies that
        only fields containing special
        characters are quoted (e.g., characters defined
        in ``quotechar``, ``delimiter``,
        or ``lineterminator``.
    doublequote : bool, default True
        When ``quotechar`` is specified and ``quoting`` is not ``QUOTE_NONE``, indicate
        whether or not to interpret two consecutive ``quotechar`` elements INSIDE a
        field as a single ``quotechar`` element.
    escapechar : str (length 1), optional
        Character used to escape other characters.
    comment : str (length 1), optional
        Character indicating that the remainder of line should not be parsed.
        If found at the beginning
        of a line, the line will be ignored altogether. This parameter must be a
        single character. Like empty lines (as long as ``skip_blank_lines=True``),
        fully commented lines are ignored by the parameter ``header`` but not by
        ``skiprows``. For example, if ``comment='#'``, parsing
        ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in ``'a,b,c'`` being
        treated as the header.
    encoding : str, optional, default 'utf-8'
        Encoding to use for UTF when reading/writing (ex. ``'utf-8'``). `List of Python
        standard encodings
        <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

    encoding_errors : str, optional, default 'strict'
        How encoding errors are treated. `List of possible values
        <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

    dialect : str or csv.Dialect, optional
        If provided, this parameter will override values (default or not) for the
        following parameters: ``delimiter``, ``doublequote``, ``escapechar``,
        ``skipinitialspace``, ``quotechar``, and ``quoting``. If it is necessary to
        override values, a ``ParserWarning`` will be issued. See ``csv.Dialect``
        documentation for more details.
    on_bad_lines : {{'error', 'warn', 'skip'}} or Callable, default 'error'
        Specifies what to do upon encountering a bad line (a line with too many fields).
        Allowed values are:

        - ``'error'``, raise an Exception when a bad line is encountered.
        - ``'warn'``, raise a warning when a bad line is
          encountered and skip that line.
        - ``'skip'``, skip bad lines without raising or warning when
          they are encountered.
        - Callable, function that will process a single bad line.
            - With ``engine='python'``, function with signature
              ``(bad_line: list[str]) -> list[str] | None``.
              ``bad_line`` is a list of strings split by the ``sep``.
              If the function returns ``None``, the bad line will be ignored.
              If the function returns a new ``list`` of strings with
              more elements than
              expected, a ``ParserWarning`` will be emitted while
              dropping extra elements.
            - With ``engine='pyarrow'``, function with signature
              as described in pyarrow documentation: `invalid_row_handler
              <https://arrow.apache.org/docs/python
              /generated/pyarrow.csv.ParseOptions.html
              #pyarrow.csv.ParseOptions.invalid_row_handler>`_.

        .. versionchanged:: 2.2.0

            Callable for ``engine='pyarrow'``

    low_memory : bool, default True
        Internally process the file in chunks, resulting in lower memory use
        while parsing, but possibly mixed type inference.  To ensure no mixed
        types either set ``False``, or specify the type with the ``dtype`` parameter.
        Note that the entire file is read into a single :class:`~pandas.DataFrame`
        regardless, use the ``chunksize`` or ``iterator``
        parameter to return the data in
        chunks. (Only valid with C parser).
    memory_map : bool, default False
        If a filepath is provided for ``filepath_or_buffer``, map the file object

help() ile dokumantasyona ulasabiliriz

In [9]:
#df = pd.DataFrame(pd.read_csv("hepsiemlak.csv"))

In [10]:
#df

In [11]:
#dir(df)

In [12]:
#df.info()

In [13]:
dir(os)

['DirEntry',
 'EX_OK',
 'F_OK',
 'GenericAlias',
 'Mapping',
 'MutableMapping',
 'O_APPEND',
 'O_BINARY',
 'O_CREAT',
 'O_EXCL',
 'O_NOINHERIT',
 'O_RANDOM',
 'O_RDONLY',
 'O_RDWR',
 'O_SEQUENTIAL',
 'O_SHORT_LIVED',
 'O_TEMPORARY',
 'O_TEXT',
 'O_TRUNC',
 'O_WRONLY',
 'P_DETACH',
 'P_NOWAIT',
 'P_NOWAITO',
 'P_OVERLAY',
 'P_WAIT',
 'PathLike',
 'R_OK',
 'SEEK_CUR',
 'SEEK_END',
 'SEEK_SET',
 'TMP_MAX',
 'W_OK',
 'X_OK',
 '_AddedDllDirectory',
 '_Environ',
 '__all__',
 '__builtins__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_check_methods',
 '_execvpe',
 '_exists',
 '_exit',
 '_fspath',
 '_get_exports_list',
 '_walk_symlinks_as_files',
 '_wrap_close',
 'abc',
 'abort',
 'access',
 'add_dll_directory',
 'altsep',
 'chdir',
 'chmod',
 'close',
 'closerange',
 'cpu_count',
 'curdir',
 'defpath',
 'device_encoding',
 'devnull',
 'dup',
 'dup2',
 'environ',
 'error',
 'execl',
 'execle',
 'execlp',
 'execlpe',
 'execv',
 'execve',
 'execvp',
 'execvpe',
 'extsep',
 'fchmod',
 'fdopen',
 'fsdecode',
 'fsencode',
 'fspath',
 'fstat',
 'fsync',
 'ftruncate',
 'get_blocking',
 'get_exec_path',
 'get_handle_inheritable',
 'get_inheritable',
 'get_terminal_size',
 'getcwd',
 'getcwdb',
 'getenv',
 'getlogin',
 'getpid',
 'getppid',
 'isatty',
 'kill',
 'lchmod',
 'linesep',
 'link',
 'listdir',
 'listdrives',
 'listmounts',
 'listvolumes',
 'lseek',
 'lstat',
 'makedirs',
 'mkdir',
 'name',
 'open',
 'pardir',
 'path',
 'pathsep',
 'pipe',
 'popen',
 'process_cpu_count',
 'putenv',
 'read',
 'readlink',
 'remove',
 'removedirs',
 'rename',
 'renames',
 'replace',
 'rmdir',
 'scandir',
 'sep',
 'set_blocking',
 'set_handle_inheritable',
 'set_inheritable',
 'spawnl',
 'spawnle',
 'spawnv',
 'spawnve',
 'st',
 'startfile',
 'stat',
 'stat_result',
 'statvfs_result',
 'strerror',
 'supports_bytes_environ',
 'supports_dir_fd',
 'supports_effective_ids',
 'supports_fd',
 'supports_follow_symlinks',
 'symlink',
 'sys',
 'system',
 'terminal_size',
 'times',
 'times_result',
 'truncate',
 'umask',
 'uname_result',
 'unlink',
 'unsetenv',
 'urandom',
 'utime',
 'waitpid',
 'waitstatus_to_exitcode',
 'walk',
 'write']

In [14]:
help(os.listdir)

Help on built-in function listdir in module nt:

listdir(path=None)
    Return a list containing the names of the files in the directory.

    path can be specified as either str, bytes, or a path-like object.  If path is bytes,
      the filenames returned will also be bytes; in all other circumstances
      the filenames returned will be str.
    If path is None, uses the path='.'.
    On some platforms, path may also be specified as an open file descriptor;\
      the file descriptor must refer to a directory.
      If this functionality is unavailable, using it raises NotImplementedError.

    The list is in arbitrary order.  It does not include the special
    entries '.' and '..' even if they are present in the directory.

In [15]:
files = os.listdir(path="hepsiemlak/")

In [16]:
df = pd.concat([pd.read_csv(f"hepsiemlak/{file}") for file in files],ignore_index=True)

hepsiemlak klasorunun icindeki dosyaları dongu ile dolasırken concat fonksiyonu ile bunları birleştiriyoruz ignore_index=True ile her yeni csv dosyasında sıfırdan başlamak yerine data frame'de kaldıgı yerden devam etmesini sağlıyoruz

In [17]:
df.shape

(8136, 18)

In [18]:
help(pd.concat)

Help on function concat in module pandas:

concat(
    objs: 'Iterable[Series | DataFrame] | Mapping[HashableT, Series | DataFrame]',
    *,
    axis: 'Axis' = 0,
    join: 'str' = 'outer',
    ignore_index: 'bool' = False,
    keys: 'Iterable[Hashable] | None' = None,
    levels=None,
    names: 'list[HashableT] | None' = None,
    verify_integrity: 'bool' = False,
    sort: 'bool | lib.NoDefault' = <no_default>,
    copy: 'bool | lib.NoDefault' = <no_default>
) -> 'DataFrame | Series'
    Concatenate pandas objects along a particular axis.

    Allows optional set logic along the other axes.

    Can also add a layer of hierarchical indexing on the concatenation axis,
    which may be useful if the labels are the same (or overlapping) on
    the passed axis number.

    Parameters
    ----------
    objs : an iterable or mapping of Series or DataFrame objects
        If a mapping is passed, the keys will be used as the `keys`
        argument, unless it is passed, in which case the values will be
        selected (see below). Any None objects will be dropped silently unless
        they are all None in which case a ValueError will be raised.
    axis : {0/'index', 1/'columns'}, default 0
        The axis to concatenate along.
    join : {'inner', 'outer'}, default 'outer'
        How to handle indexes on other axis (or axes).
    ignore_index : bool, default False
        If True, do not use the index values along the concatenation axis. The
        resulting axis will be labeled 0, ..., n - 1. This is useful if you are
        concatenating objects where the concatenation axis does not have
        meaningful indexing information. Note the index values on the other
        axes are still respected in the join.
    keys : sequence, default None
        If multiple levels passed, should contain tuples. Construct
        hierarchical index using the passed keys as the outermost level.
    levels : list of sequences, default None
        Specific levels (unique values) to use for constructing a
        MultiIndex. Otherwise they will be inferred from the keys.
    names : list, default None
        Names for the levels in the resulting hierarchical index.
    verify_integrity : bool, default False
        Check whether the new concatenated axis contains duplicates. This can
        be very expensive relative to the actual data concatenation.
    sort : bool, default False
        Sort non-concatenation axis. One exception to this is when the
        non-concatenation axis is a DatetimeIndex and join='outer' and the axis is
        not already aligned. In that case, the non-concatenation axis is always
        sorted lexicographically.
    copy : bool, default False
        This keyword is now ignored; changing its value will have no
        impact on the method.

        .. deprecated:: 3.0.0

            This keyword is ignored and will be removed in pandas 4.0. Since
            pandas 3.0, this method always returns a new object using a lazy
            copy mechanism that defers copies until necessary
            (Copy-on-Write). See the `user guide on Copy-on-Write
            <https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html>`__
            for more details.

    Returns
    -------
    object, type of objs
        When concatenating all ``Series`` along the index (axis=0), a
        ``Series`` is returned. When ``objs`` contains at least one
        ``DataFrame``, a ``DataFrame`` is returned. When concatenating along
        the columns (axis=1), a ``DataFrame`` is returned.

    See Also
    --------
    DataFrame.join : Join DataFrames using indexes.
    DataFrame.merge : Merge DataFrames by indexes or columns.

    Notes
    -----
    The keys, levels, and names arguments are all optional.

    A walkthrough of how this method fits in with other tools for combining
    pandas objects can be found `here
    <https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html>`__.

    It is not recommended to build DataFrames by adding single rows in a
    for loop. Build a list of rows and make a DataFrame in a single concat.

    Examples
    --------
    Combine two ``Series``.

    >>> s1 = pd.Series(["a", "b"])
    >>> s2 = pd.Series(["c", "d"])
    >>> pd.concat([s1, s2])
    0    a
    1    b
    0    c
    1    d
    dtype: str

    Clear the existing index and reset it in the result
    by setting the ``ignore_index`` option to ``True``.

    >>> pd.concat([s1, s2], ignore_index=True)
    0    a
    1    b
    2    c
    3    d
    dtype: str

    Add a hierarchical index at the outermost level of
    the data with the ``keys`` option.

    >>> pd.concat([s1, s2], keys=["s1", "s2"])
    s1  0    a
        1    b
    s2  0    c
        1    d
    dtype: str

    Label the index keys you create with the ``names`` option.

    >>> pd.concat([s1, s2], keys=["s1", "s2"], names=["Series name", "Row ID"])
    Series name  Row ID
    s1           0         a
                 1         b
    s2           0         c
                 1         d
    dtype: str

    Combine two ``DataFrame`` objects with identical columns.

    >>> df1 = pd.DataFrame([["a", 1], ["b", 2]], columns=["letter", "number"])
    >>> df1
      letter  number
    0      a       1
    1      b       2
    >>> df2 = pd.DataFrame([["c", 3], ["d", 4]], columns=["letter", "number"])
    >>> df2
      letter  number
    0      c       3
    1      d       4
    >>> pd.concat([df1, df2])
      letter  number
    0      a       1
    1      b       2
    0      c       3
    1      d       4

    Combine ``DataFrame`` objects with overlapping columns
    and return everything. Columns outside the intersection will
    be filled with ``NaN`` values.

    >>> df3 = pd.DataFrame(
    ...     [["c", 3, "cat"], ["d", 4, "dog"]], columns=["letter", "number", "animal"]
    ... )
    >>> df3
      letter  number animal
    0      c       3    cat
    1      d       4    dog
    >>> pd.concat([df1, df3], sort=False)
      letter  number animal
    0      a       1    NaN
    1      b       2    NaN
    0      c       3    cat
    1      d       4    dog

    Combine ``DataFrame`` objects with overlapping columns
    and return only those that are shared by passing ``inner`` to
    the ``join`` keyword argument.

    >>> pd.concat([df1, df3], join="inner")
      letter  number
    0      a       1
    1      b       2
    0      c       3
    1      d       4

    Combine ``DataFrame`` objects horizontally along the x axis by
    passing in ``axis=1``.

    >>> df4 = pd.DataFrame(
    ...     [["bird", "polly"], ["monkey", "george"]], columns=["animal", "name"]
    ... )
    >>> pd.concat([df1, df4], axis=1)
      letter  number  animal    name
    0      a       1    bird   polly
    1      b       2  monkey  george

    Prevent the result from including duplicate index values with the
    ``verify_integrity`` option.

    >>> df5 = pd.DataFrame([1], index=["a"])
    >>> df5
       0
    a  1
    >>> df6 = pd.DataFrame([2], index=["a"])
    >>> df6
       0
    a  2
    >>> pd.concat([df5, df6], verify_integrity=True)
    Traceback (most recent call last):
        ...
    ValueError: Indexes have overlapping values: ['a']

    Append a single row to the end of a ``DataFrame`` object.

    >>> df7 = pd.DataFrame({"a": 1, "b": 2}, index=[0])
    >>> df7
        a   b
    0   1   2
    >>> new_row = pd.Series({"a": 3, "b": 4})
    >>> new_row
    a    3
    b    4
    dtype: int64
    >>> pd.concat([df7, new_row.to_frame().T], ignore_index=True)
        a   b
    0   1   2
    1   3   4

In [19]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   img-link href        8136 non-null   str
 1   photo-count          8130 non-null   float64
 2   list-view-price      8136 non-null   object
 3   list-view-date       8136 non-null   str
 4   left                 8114 non-null   str
 5   celly                8136 non-null   str
 6   celly 2              8136 non-null   str
 7   celly 3              8136 non-null   str
 8   celly 4              6858 non-null   str
 9   list-view-location   8136 non-null   str
 10  img-wrp href         4555 non-null   str
 11  he-lazy-image src    7649 non-null   str
 12  he-lazy-image src 2  4067 non-null   str
 13  list-view-header     8129 non-null   str
 14  branded__text        134 non-null    str
 15  branded__text 2      134 non-null    str
 16  img-wrp href 2       133 non-null    str
 17  he-lazy-image src 3  116 non-null    str
dtypes: float64(1), object(1), str(16)
memory usage: 1.1+ MB
None

In [20]:
dir(df)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append_internal',
 '_arith_method',
 '_arith_method_with_reindex',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_copy_deprecation',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_label_or_level_ambiguity',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'between_time',
 'bfill',
 'boxplot',
 'branded__text',
 'celly',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_arrow',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last_valid_index',
 'le',
 'left',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_hdf',
 'to_html',
 'to_iceberg',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [21]:
df.sample()

,img-link href,photo-count,list-view-price,list-view-date,left,celly,celly 2,celly 3,celly 4,list-view-location,img-wrp href,he-lazy-image src,he-lazy-image src 2,list-view-header,branded__text,branded__text 2,img-wrp href 2,he-lazy-image src 3
2103,https://www.hepsiemlak.com/izmir-konak-mimar-s...,18.0,19.000,15-04-2024,Kiralık Daire,3 +\n 1,140 m²,30\n Yaşında,4. Kat,"Konak, Mimar Sinan Mahallesi",NaN,https://hecdn01.hemlak.com/mncropresize/182/13...,NaN,Trt Fuar Ve Gazi Hastanesi Yakını Eşyalı Büyük...,NaN,NaN,NaN,NaN

In [22]:
df.tail() #data frame'de sondan 5 degeri getirir

,img-link href,photo-count,list-view-price,list-view-date,left,celly,celly 2,celly 3,celly 4,list-view-location,img-wrp href,he-lazy-image src,he-lazy-image src 2,list-view-header,branded__text,branded__text 2,img-wrp href 2,he-lazy-image src 3
8131,https://www.hepsiemlak.com/mugla-bodrum-gumusl...,21.0,160.000,15-04-2024,Kiralık Villa,2 +\n 1,135 m²,8\n Yaşında,NaN,"Bodrum, Gümüşlük Mahallesi",https://www.hepsiemlak.com/emlak-ofisi/keller-...,https://hecdn01.hemlak.com/mncropresize/182/13...,https://hecdnnw.hemlak.com/mncropresize/91/68/...,Gümüşlükde Bayram Haftası Kiralık,NaN,NaN,NaN,NaN
8132,https://www.hepsiemlak.com/mugla-bodrum-golkoy...,21.0,160.000,06-04-2024,Kiralık Daire,2 +\n 1,120 m²,1\n Yaşında,Bahçe Katı,"Bodrum, Gölköy Mahallesi",https://www.hepsiemlak.com/emlak-ofisi/bodrum-...,https://hecdn01.hemlak.com/mncropresize/182/13...,https://hecdnnw.hemlak.com/mncropresize/91/68/...,Gölköy Denize 50 Adım,NaN,NaN,NaN,NaN
8133,https://www.hepsiemlak.com/mugla-mentese-yenik...,9.0,9.000,15-03-2024,Kiralık Daire,1 +\n 1,50 m²,12\n Yaşında,2. Kat,"Menteşe, Yeniköy Mahallesi",NaN,https://hecdn01.hemlak.com/mncropresize/182/13...,NaN,Muğla Yeniköy Mah. Eşyalı 1+1 Kiralık Daire,NaN,NaN,NaN,NaN
8134,https://www.hepsiemlak.com/mugla-bodrum-turkbu...,17.0,620.000,18-03-2024,Kiralık Yazlık,2 +\n 1,98 m²,6\n Yaşında,Bahçe Katı,"Bodrum, Türkbükü Mahallesi",https://www.hepsiemlak.com/emlak-ofisi/keller-...,https://hecdn01.hemlak.com/mncropresize/182/13...,https://hecdnnw.hemlak.com/mncropresize/91/68/...,Türkbükü Sahiline 150 Metre,NaN,NaN,NaN,NaN
8135,https://www.hepsiemlak.com/mugla-ortaca-cayli-...,18.0,15.000,03-03-2024,Kiralık Daire,3 +\n 1,150 m²,5\n Yaşında,Yüksek Giriş,"Ortaca, Çaylı Mahallesi",https://www.hepsiemlak.com/emlak-ofisi/elit-em...,https://hecdn01.hemlak.com/mncropresize/182/13...,https://hecdnnw.hemlak.com/mncropresize/91/68/...,Ortaca Çaylı Da 3+1 Kiralik Geniş Daire,NaN,NaN,NaN,NaN

In [23]:
help(df.sample)

Help on method sample in module pandas.core.generic:

sample(
    n: 'int | None' = None,
    frac: 'float | None' = None,
    replace: 'bool' = False,
    weights=None,
    random_state: 'RandomState | None' = None,
    axis: 'Axis | None' = None,
    ignore_index: 'bool' = False
) -> 'Self' method of pandas.DataFrame instance
    Return a random sample of items from an axis of object.

    You can use `random_state` for reproducibility.

    Parameters
    ----------
    n : int, optional
        Number of items from axis to return. Cannot be used with `frac`.
        Default = 1 if `frac` = None.
    frac : float, optional
        Fraction of axis items to return. Cannot be used with `n`.
    replace : bool, default False
        Allow or disallow sampling of the same row more than once.
    weights : str or ndarray-like, optional
        Default ``None`` results in equal probability weighting.
        If passed a Series, will align with target object on index. Index
        values in weights not found in sampled object will be ignored and
        index values in sampled object not in weights will be assigned
        weights of zero.
        If called on a DataFrame, will accept the name of a column
        when axis = 0.
        Unless weights are a Series, weights must be same length as axis
        being sampled.
        If weights do not sum to 1, they will be normalized to sum to 1.
        Missing values in the weights column will be treated as zero.
        Infinite values not allowed.
        When replace = False will not allow ``(n * max(weights) / sum(weights)) > 1``
        in order to avoid biased results. See the Notes below for more details.
    random_state : int, array-like, BitGenerator, np.random.RandomState, np.random.Generator, optional
        If int, array-like, or BitGenerator, seed for random number generator.
        If np.random.RandomState or np.random.Generator, use as given.
        Default ``None`` results in sampling with the current state of np.random.
    axis : {0 or 'index', 1 or 'columns', None}, default None
        Axis to sample. Accepts axis number or name. Default is stat axis
        for given data type. For `Series` this parameter is unused and defaults to `None`.
    ignore_index : bool, default False
        If True, the resulting index will be labeled 0, 1, …, n - 1.

    Returns
    -------
    Series or DataFrame
        A new object of same type as caller containing `n` items randomly
        sampled from the caller object.

    See Also
    --------
    DataFrameGroupBy.sample: Generates random samples from each group of a
        DataFrame object.
    SeriesGroupBy.sample: Generates random samples from each group of a
        Series object.
    numpy.random.choice: Generates a random sample from a given 1-D numpy
        array.

    Notes
    -----
    If `frac` > 1, `replacement` should be set to `True`.

    When replace = False will not allow ``(n * max(weights) / sum(weights)) > 1``,
    since that would cause results to be biased. E.g. sampling 2 items without replacement
    with weights [100, 1, 1] would yield two last items in 1/2 of cases, instead of 1/102.
    This is similar to specifying `n=4` without replacement on a Series with 3 elements.

    Examples
    --------
    >>> df = pd.DataFrame(
    ...     {
    ...         "num_legs": [2, 4, 8, 0],
    ...         "num_wings": [2, 0, 0, 0],
    ...         "num_specimen_seen": [10, 2, 1, 8],
    ...     },
    ...     index=["falcon", "dog", "spider", "fish"],
    ... )
    >>> df
            num_legs  num_wings  num_specimen_seen
    falcon         2          2                 10
    dog            4          0                  2
    spider         8          0                  1
    fish           0          0                  8

    Extract 3 random elements from the ``Series`` ``df['num_legs']``:
    Note that we use `random_state` to ensure the reproducibility of
    the examples.

    >>> df["num_legs"].sample(n=3, random_state=1)
    fish      0
    spider    8
    falcon    2
    Name: num_legs, dtype: int64

    A random 50% sample of the ``DataFrame`` with replacement:

    >>> df.sample(frac=0.5, replace=True, random_state=1)
          num_legs  num_wings  num_specimen_seen
    dog          4          0                  2
    fish         0          0                  8

    An upsample sample of the ``DataFrame`` with replacement:
    Note that `replace` parameter has to be `True` for `frac` parameter > 1.

    >>> df.sample(frac=2, replace=True, random_state=1)
            num_legs  num_wings  num_specimen_seen
    dog            4          0                  2
    fish           0          0                  8
    falcon         2          2                 10
    falcon         2          2                 10
    fish           0          0                  8
    dog            4          0                  2
    fish           0          0                  8
    dog            4          0                  2

    Using a DataFrame column as weights. Rows with larger value in the
    `num_specimen_seen` column are more likely to be sampled.

    >>> df.sample(n=2, weights="num_specimen_seen", random_state=1)
            num_legs  num_wings  num_specimen_seen
    falcon         2          2                 10
    fish           0          0                  8

In [24]:
dir(df)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append_internal',
 '_arith_method',
 '_arith_method_with_reindex',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_copy_deprecation',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_label_or_level_ambiguity',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'between_time',
 'bfill',
 'boxplot',
 'branded__text',
 'celly',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_arrow',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last_valid_index',
 'le',
 'left',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_hdf',
 'to_html',
 'to_iceberg',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [25]:
help(df.drop)

Help on method drop in module pandas.core.frame:

drop(
    labels: 'IndexLabel | ListLike' = None,
    *,
    axis: 'Axis' = 0,
    index: 'IndexLabel | ListLike' = None,
    columns: 'IndexLabel | ListLike' = None,
    level: 'Level | None' = None,
    inplace: 'bool' = False,
    errors: 'IgnoreRaise' = 'raise'
) -> 'DataFrame | None' method of pandas.DataFrame instance
    Drop specified labels from rows or columns.

    Remove rows or columns by specifying label names and corresponding
    axis, or by directly specifying index or column names. When using a
    multi-index, labels on different levels can be removed by specifying
    the level. See the :ref:`user guide <advanced.shown_levels>`
    for more information about the now unused levels.

    Parameters
    ----------
    labels : single label or iterable of labels
        Index or column labels to drop. A tuple will be used as a single
        label and not treated as an iterable.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Whether to drop labels from the index (0 or 'index') or
        columns (1 or 'columns').
    index : single label or iterable of labels
        Alternative to specifying axis (``labels, axis=0``
        is equivalent to ``index=labels``).
    columns : single label or iterable of labels
        Alternative to specifying axis (``labels, axis=1``
        is equivalent to ``columns=labels``).
    level : int or level name, optional
        For MultiIndex, level from which the labels will be removed.
    inplace : bool, default False
        If False, return a copy. Otherwise, do operation
        in place and return None.
    errors : {'ignore', 'raise'}, default 'raise'
        If 'ignore', suppress error and only existing labels are
        dropped.

    Returns
    -------
    DataFrame or None
        Returns DataFrame or None DataFrame with the specified
        index or column labels removed or None if inplace=True.

    Raises
    ------
    KeyError
        If any of the labels is not found in the selected axis.

    See Also
    --------
    DataFrame.loc : Label-location based indexer for selection by label.
    DataFrame.dropna : Return DataFrame with labels on given axis omitted
        where (all or any) data are missing.
    DataFrame.drop_duplicates : Return DataFrame with duplicate rows
        removed, optionally only considering certain columns.
    Series.drop : Return Series with specified index labels removed.

    Examples
    --------
    >>> df = pd.DataFrame(np.arange(12).reshape(3, 4), columns=["A", "B", "C", "D"])
    >>> df
       A  B   C   D
    0  0  1   2   3
    1  4  5   6   7
    2  8  9  10  11

    Drop columns

    >>> df.drop(["B", "C"], axis=1)
       A   D
    0  0   3
    1  4   7
    2  8  11

    >>> df.drop(columns=["B", "C"])
       A   D
    0  0   3
    1  4   7
    2  8  11

    Drop a row by index

    >>> df.drop([0, 1])
       A  B   C   D
    2  8  9  10  11

    Drop columns and/or rows of MultiIndex DataFrame

    >>> midx = pd.MultiIndex(
    ...     levels=[["llama", "cow", "falcon"], ["speed", "weight", "length"]],
    ...     codes=[[0, 0, 0, 1, 1, 1, 2, 2, 2], [0, 1, 2, 0, 1, 2, 0, 1, 2]],
    ... )
    >>> df = pd.DataFrame(
    ...     index=midx,
    ...     columns=["big", "small"],
    ...     data=[
    ...         [45, 30],
    ...         [200, 100],
    ...         [1.5, 1],
    ...         [30, 20],
    ...         [250, 150],
    ...         [1.5, 0.8],
    ...         [320, 250],
    ...         [1, 0.8],
    ...         [0.3, 0.2],
    ...     ],
    ... )
    >>> df
                    big     small
    llama   speed   45.0    30.0
            weight  200.0   100.0
            length  1.5     1.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
            length  1.5     0.8
    falcon  speed   320.0   250.0
            weight  1.0     0.8
            length  0.3     0.2

    Drop a specific index combination from the MultiIndex
    DataFrame, i.e., drop the combination ``'falcon'`` and
    ``'weight'``, which deletes only the corresponding row

    >>> df.drop(index=("falcon", "weight"))
                    big     small
    llama   speed   45.0    30.0
            weight  200.0   100.0
            length  1.5     1.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
            length  1.5     0.8
    falcon  speed   320.0   250.0
            length  0.3     0.2

    >>> df.drop(index="cow", columns="small")
                    big
    llama   speed   45.0
            weight  200.0
            length  1.5
    falcon  speed   320.0
            weight  1.0
            length  0.3

    >>> df.drop(index="length", level=1)
                    big     small
    llama   speed   45.0    30.0
            weight  200.0   100.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
    falcon  speed   320.0   250.0
            weight  1.0     0.8

In [26]:
df.columns

Index(['img-link href', 'photo-count', 'list-view-price', 'list-view-date',
       'left', 'celly', 'celly 2', 'celly 3', 'celly 4', 'list-view-location',
       'img-wrp href', 'he-lazy-image src', 'he-lazy-image src 2',
       'list-view-header', 'branded__text', 'branded__text 2',
       'img-wrp href 2', 'he-lazy-image src 3'],
      dtype='str')

In [27]:
silinecekSutunlar = ['photo-count','list-view-date','left',
       'img-wrp href', 'he-lazy-image src', 'he-lazy-image src 2',
       'list-view-header', 'branded__text', 'branded__text 2',
       'img-wrp href 2', 'he-lazy-image src 3','list-view-location']
for sutun in silinecekSutunlar:
       try:
              df.drop(sutun,axis=1,inplace=True)
       except Exception as e:
              print(f"Bir hata oluştu : {e}")

sadece bir sütünu yazmayı unutmuş olabiliriz bu gibi senaryolarda programın cokmesini onlemek icin try except kullanabiliriz bu sayede bir sutunu yazmamış olsak bile sonradan ekleme yapabiliriz.

axis=1 sütün silme,
kalıcı şekilde silmek icin (data frame üzerinde işlem yapmak icin) inplace=True

In [28]:
df.head()

,img-link href,list-view-price,celly,celly 2,celly 3,celly 4
0,https://www.hepsiemlak.com/izmir-konak-kilic-r...,12.000,1 +\n 1,55 m²,25\n Yaşında,Yüksek Giriş
1,https://www.hepsiemlak.com/izmir-konak-akin-si...,16.000,3 +\n 1,150 m²,35\n Yaşında,3. Kat
2,https://www.hepsiemlak.com/izmir-buca-adatepe-...,200,2 +\n 1,55 m²,2\n Yaşında,Ara Kat
3,https://www.hepsiemlak.com/izmir-buca-yaylacik...,200,2 +\n 1,60 m²,2\n Yaşında,3. Kat
4,https://www.hepsiemlak.com/izmir-karsiyaka-bah...,18.000,3 +\n 1,160 m²,27\n Yaşında,3. Kat

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   img-link href    8136 non-null   str
 1   list-view-price  8136 non-null   object
 2   celly            8136 non-null   str
 3   celly 2          8136 non-null   str
 4   celly 3          8136 non-null   str
 5   celly 4          6858 non-null   str
dtypes: object(1), str(5)
memory usage: 381.5+ KB

In [30]:
print(df["img-link href"].unique())

<StringArray>
[      'https://www.hepsiemlak.com/izmir-konak-kilic-reis-kiralik/daire/130125-62',
       'https://www.hepsiemlak.com/izmir-konak-akin-simav-kiralik/daire/130125-91',
           'https://www.hepsiemlak.com/izmir-buca-adatepe-kiralik/daire/138098-14',
          'https://www.hepsiemlak.com/izmir-buca-yaylacik-kiralik/daire/138098-16',
 'https://www.hepsiemlak.com/izmir-karsiyaka-bahcelievler-kiralik/daire/99733-310',
           'https://www.hepsiemlak.com/izmir-konak-kultur-kiralik/daire/99733-349',
    'https://www.hepsiemlak.com/izmir-bornova-kazimdirik-kiralik/daire/125039-332',
        'https://www.hepsiemlak.com/izmir-gaziemir-yesil-kiralik/daire/94107-1368',
       'https://www.hepsiemlak.com/izmir-gaziemir-atifbey-kiralik/daire/94107-932',
  'https://www.hepsiemlak.com/izmir-gaziemir-dokuz-eylul-kiralik/daire/94107-1363',
 ...
   'https://www.hepsiemlak.com/mugla-bodrum-turkbuku-kiralik/mustakil-ev/120934-6',
        'https://www.hepsiemlak.com/mugla-bodrum-turkbuku-kiralik/villa/5343-9663',
       'https://www.hepsiemlak.com/mugla-bodrum-kucukbuk-kiralik/daire/5343-10164',
     'https://www.hepsiemlak.com/mugla-bodrum-golkoy-kiralik/mustakil-ev/120934-4',
       'https://www.hepsiemlak.com/mugla-ortaca-kemaliye-kiralik/daire/82884-1207',
        'https://www.hepsiemlak.com/mugla-bodrum-gumusluk-kiralik/villa/5343-9764',
          'https://www.hepsiemlak.com/mugla-bodrum-golkoy-kiralik/daire/120934-54',
       'https://www.hepsiemlak.com/mugla-mentese-yenikoy-kiralik/daire/76834-2215',
       'https://www.hepsiemlak.com/mugla-bodrum-turkbuku-kiralik/yazlik/5343-8596',
          'https://www.hepsiemlak.com/mugla-ortaca-cayli-kiralik/daire/82884-1210']
Length: 8131, dtype: str

In [31]:
stringDeger = 'https://www.hepsiemlak.com/izmir-konak-kilic-reis-kiralik/daire/130125-62'

In [32]:
dir(stringDeger)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

In [33]:
help(stringDeger.split)

Help on built-in function split:

split(sep=None, maxsplit=-1) method of builtins.str instance
    Return a list of the substrings in the string, using sep as the separator string.

      sep
        The separator used to split the string.

        When set to None (the default value), will split on any whitespace
        character (including \n \r \t \f and spaces) and will discard
        empty strings from the result.
      maxsplit
        Maximum number of splits.
        -1 (the default value) means no limit.

    Splitting starts at the front of the string and works to the end.

    Note, str.split() is mainly useful for data that has been intentionally
    delimited.  With natural text that includes punctuation, consider using
    the regular expression module.

In [34]:
a = stringDeger.split(sep="/",maxsplit=4)

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   img-link href    8136 non-null   str
 1   list-view-price  8136 non-null   object
 2   celly            8136 non-null   str
 3   celly 2          8136 non-null   str
 4   celly 3          8136 non-null   str
 5   celly 4          6858 non-null   str
dtypes: object(1), str(5)
memory usage: 381.5+ KB

In [36]:
#imgLinkHref = df["img-link href"].str.split("/")

In [37]:
#imgLinkHref.str[3].str.split("-")

In [42]:
df["location"] = df["img-link href"].apply(lambda x: x.split("/")[3])
df["city"] = df["location"].str.split("-").str[0]
df["district"] = df["location"].str.split("-").str[1]
df["neighborhood"] = df["location"].str.split("-").str[2:-1] 
df["neighborhood"] = df["neighborhood"].apply(lambda x: "_".join(x))

mugla-bodrum-turkbuku-kiralik

izmir-seferihisar-colak-ibrahim-bey-kiralik

sıfırıncı indexte şehirler, birinci indexte ilçeler, ondan sonra gelen indexlerde ise mahalle adları var ama son indexi kullanmayacagız mahalle adi ikinci indexten sondan birinci indexe kadar

join() fonksiyonu ile stringleri aralarında " " (joinden hemen once kullandıgımız deger) ile birlestiriyoruz

In [43]:
drop_columns(df,["location","img-link href"])

In [44]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   list-view-price  8136 non-null   object
 1   celly            8136 non-null   str
 2   celly 2          8136 non-null   str
 3   celly 3          8136 non-null   str
 4   celly 4          6858 non-null   str
 5   city             8136 non-null   object
 6   district         8136 non-null   object
 7   neighborhood     8136 non-null   str
dtypes: object(3), str(5)
memory usage: 508.6+ KB

In [45]:
print(df[["city","district","neighborhood"]].sample(50))

         city      district                  neighborhood
1075    izmir      gaziemir                         sevgi
3460    izmir     kemalpasa  ulucak_mustafa_kemal_ataturk
5236  denizli     pamukkale                 dokuzkavaklar
816     izmir       bornova                       kizilay
4747    aydin      kusadasi                           ege
2791    izmir         cesme                      reisdere
327     izmir     karsiyaka                      bostanli
5222  denizli  merkezefendi                   degirmenonu
3903  kutahya        merkez                       alipasa
1876    izmir          buca                     buca_koop
3227    izmir         cesme                       alacati
7633    mugla        bodrum                        gumbet
4757    aydin        efeler                      kurtulus
2339    izmir         cesme                       musalla
1634    izmir     narlidere                       2_inonu
1325    izmir          buca                       adatepe
159     izmir          urla                       torasan
4234    aydin      kusadasi                 hacifeyzullah
1935    izmir         konak                    murat_reis
319     izmir    karabaglar                   metin_oktay
1787    izmir        odemis                       bengisu
1307    izmir          urla                     sirinkent
271     izmir       torbali                    yedi_eylul
3381    izmir         cesme                        dalyan
6784    mugla      marmaris                     armutalan
2574    izmir       bornova                    kazimdirik
1898    izmir     karsiyaka                      ornekkoy
5030  denizli     pamukkale                   asmalievler
3653    izmir       menemen                         irmak
5082  denizli     pamukkale                        atalar
7411    mugla        ortaca                     tepearasi
600     izmir    karabaglar                      uzundere
2996    izmir      bayrakli                 r_sevket_ince
6423    mugla        bodrum                        gumbet
26      izmir         konak                    kilic_reis
2562    izmir       bornova                    kazimdirik
228     izmir     karsiyaka                  bahcelievler
379     izmir       bornova                       mevlana
1947    izmir         cesme                          yali
5049  denizli     pamukkale                      15_mayis
2482    izmir    guzelbahce                  kahramandere
2014    izmir          urla                      gulbahce
4820  denizli     pamukkale                      kuspinar
2977    izmir         cesme                       alacati
7247    mugla        bodrum                      kucukbuk
5538  denizli     pamukkale                    pelitlibag
4370    aydin         didim                         hisar
274     izmir    karabaglar                         vatan
4590    aydin      kusadasi                       karaova
235     izmir         cesme                       alacati

In [46]:
print(df.columns)

Index(['list-view-price', 'celly', 'celly 2', 'celly 3', 'celly 4', 'city',
       'district', 'neighborhood'],
      dtype='str')

In [57]:
print(df["celly"].sample(10))

4034    2 +\n                        1
6837    2 +\n                        1
6911    2 +\n                        1
6323    2 +\n                        1
7290    2 +\n                        1
1565    2 +\n                        1
4643    2 +\n                        1
7196    3 +\n                        1
2110    4 +\n                        1
2684    2 +\n                        1
Name: celly, dtype: str

In [54]:
df["celly"].unique()

<StringArray>
[ '1 +\n                        1',  '3 +\n                        1',
  '2 +\n                        1',  '4 +\n                        1',
  '4 +\n                        2',  '5 +\n                        1',
  '6 +\n                        1',  '7 +\n                        1',
 '21 +\n                        1',  '6 +\n                        2',
  '5 +\n                        2',                          'Stüdyo',
  '7 +\n                        2',  '3 +\n                        2',
  '2 +\n                        0',  '6 +\n                        0',
  '9 +\n                        4',  '9 +\n                        1',
  '3 +\n                        0', '1 +\n                        15',
  '2 +\n                        2',  '8 +\n                        1',
 '41 +\n                        4',  '4 +\n                        0',
 '1 +\n                        25',  '4 +\n                        4',
  '3 +\n                        4',  '1 +\n                        2',
  '3 +\n                        3', '31 +\n                        1',
  '4 +\n                        3',  '9 +\n                        5',
  '8 +\n                        4',  '4 +\n                        5',
  '9 +\n                        3', '25 +\n                        5',
  '8 +\n                        0',  '9 +\n                        9',
 '14 +\n                        6', '10 +\n                        1']
Length: 40, dtype: str

unique() tekrar eden degerleri kaldırır her degeri bir kere dondurur bu sayede kac farklı deger oldugunu gorebiliriz

In [64]:
df["celly"] = df["celly"].apply(lambda x: x.replace('Stüdyo','1 + 0'))

celly sutununda daire sayısı degerleri var bu degerlerden 'Stüdyo' olanları '1 + 0' ile degistiriyoruz

In [67]:
df["celly"] = df["celly"].apply(lambda x: x.replace('\n',''))

alt satıra gecme karakterlerini de '' ile degistirdik.

In [93]:
df["room"] = df["celly"].apply(lambda x : x.split(sep="+")[0]).astype(int)
df["living_room"] = df["celly"].apply(lambda x : x.split(sep="+")[1]).astype(int) #salon

.astype(int) ile stringden integer'a cevirme yaptık

In [95]:
df["room"].unique()

array([ 1,  3,  2,  4,  5,  6,  7, 21,  9,  8, 41, 31, 25, 14, 10])

In [96]:
df["living_room"].unique()

array([ 1,  2,  0,  4, 15, 25,  3,  5,  9,  6])

In [ ]:
drop_columns(df,['celly'])

In [101]:
print(df.columns)

Index(['list-view-price', 'celly 2', 'celly 3', 'celly 4', 'city', 'district',
       'neighborhood', 'room', 'living_room'],
      dtype='str')

In [107]:
print(list(df["celly 2"].unique()))

['55 m²', '150 m²', '60 m²', '160 m²', '135 m²', '67 m²', '140 m²', '170 m²', '130 m²', '230 m²', '220 m²', '210 m²', '89 m²', '120 m²', '200 m²', '355 m²', '75 m²', '110 m²', '100 m²', '65 m²', '145 m²', '115 m²', '1.000 m²', '250 m²', '105 m²', '50 m²', '87 m²', '90 m²', '85 m²', '155 m²', '275 m²', '240 m²', '95 m²', '174 m²', '80 m²', '125 m²', '180 m²', '165 m²', '350 m²', '97 m²', '45 m²', '300 m²', '84 m²', '42 m²', '98 m²', '86 m²', '500 m²', '70 m²', '51 m²', '73 m²', '132 m²', '325 m²', '141 m²', '450 m²', '600 m²', '47 m²', '72 m²', '71 m²', '3.000 m²', '175 m²', '320 m²', '280 m²', '156 m²', '190 m²', '78 m²', '162 m²', '185 m²', '18 m²', '330 m²', '151 m²', '56 m²', '136 m²', '131 m²', '48 m²', '580 m²', '119 m²', '147 m²', '77 m²', '245 m²', '35 m²', '375 m²', '146 m²', '161 m²', '163 m²', '149 m²', '206 m²', '138 m²', '93 m²', '63 m²', '41 m²', '183 m²', '96 m²', '108 m²', '76 m²', '475 m²', '359 m²', '124 m²', '91 m²', '194 m²', '43 m²', '4.500 m²', '68 m²', '205 m²', '20 m²', '103 m²', '53 m²', '270 m²', '58 m²', '302 m²', '505 m²', '800 m²', '168 m²', '154 m²', '368 m²', '178 m²', '40 m²', '750 m²', '92 m²', '181 m²', '400 m²', '30 m²', '260 m²', '460 m²', '390 m²', '64 m²', '360 m²', '340 m²', '550 m²', '38 m²', '121 m²', '4.000 m²', '295 m²', '112 m²', '137 m²', '22 m²', '128 m²', '3.200 m²', '440 m²', '122 m²', '370 m²', '380 m²', '204 m²', '148 m²', '142 m²', '520 m²', '166 m²', '870 m²', '143 m²', '57 m²', '286 m²', '81 m²', '116 m²', '209 m²', '59 m²', '106 m²', '74 m²', '1.301 m²', '52 m²', '167 m²', '217 m²', '25 m²', '290 m²', '196 m²', '184 m²', '159 m²', '195 m²', '640 m²', '285 m²', '235 m²', '337 m²', '211 m²', '134 m²', '832 m²', '152 m²', '88 m²', '213 m²', '126 m²', '255 m²', '199 m²', '127 m²', '11 m²', '66 m²', '399 m²', '187 m²', '341 m²', '745 m²', '118 m²', '144 m²', '15 m²', '535 m²', '5.500 m²', '114 m²', '208 m²', '94 m²', '46 m²', '173 m²', '900 m²', '225 m²', '402 m²', '111 m²', '193 m²', '1.100 m²', '212 m²', '102 m²', '177 m²', '101 m²', '164 m²', '158 m²', '62 m²', '172 m²', '9.000 m²', '21 m²', '117 m²', '82 m²', '49 m²', '176 m²', '182 m²', '981 m²', '256 m²', '32 m²', '3.510 m²', '215 m²', '1.057 m²', '171 m²', '79 m²', '169 m²', '28 m²', '104 m²', '201 m²', '310 m²', '1.150 m²', '2.000 m²', '228 m²', '700 m²', '349 m²', '203 m²', '510 m²', '31 m²', '33 m²', '950 m²', '650 m²', '252 m²', '493 m²', '265 m²', '1.400 m²', '5 m²', '113 m²', '36 m²', '317 m²', '850 m²', '249 m²', '109 m²', '420 m²', '995 m²', '545 m²', '192 m²', '1.250 m²', '490 m²', '760 m²', '157 m²', '54 m²', '405 m²', '99 m²']

In [110]:
df["celly 2"] = df["celly 2"].apply(lambda  x : x.replace(".",""))

bazı degerlerimde '5.500 m²' bunun gibi binlik sayılarda arada nokta var integera cevirmeden once bu noktaları kaldırıyorum.

In [112]:
df["area"] = df["celly 2"].apply(lambda x : x.split(" ")[0]).astype(int)

In [119]:
print(df["area"].unique())

[  55  150   60  160  135   67  140  170  130  230  220  210   89  120
  200  355   75  110  100   65  145  115 1000  250  105   50   87   90
   85  155  275  240   95  174   80  125  180  165  350   97   45  300
   84   42   98   86  500   70   51   73  132  325  141  450  600   47
   72   71 3000  175  320  280  156  190   78  162  185   18  330  151
   56  136  131   48  580  119  147   77  245   35  375  146  161  163
  149  206  138   93   63   41  183   96  108   76  475  359  124   91
  194   43 4500   68  205   20  103   53  270   58  302  505  800  168
  154  368  178   40  750   92  181  400   30  260  460  390   64  360
  340  550   38  121 4000  295  112  137   22  128 3200  440  122  370
  380  204  148  142  520  166  870  143   57  286   81  116  209   59
  106   74 1301   52  167  217   25  290  196  184  159  195  640  285
  235  337  211  134  832  152   88  213  126  255  199  127   11   66
  399  187  341  745  118  144   15  535 5500  114  208   94   46  173
  900  225  402  111  193 1100  212  102  177  101  164  158   62  172
 9000   21  117   82   49  176  182  981  256   32 3510  215 1057  171
   79  169   28  104  201  310 1150 2000  228  700  349  203  510   31
   33  950  650  252  493  265 1400    5  113   36  317  850  249  109
  420  995  545  192 1250  490  760  157   54  405   99]

In [120]:
drop_columns(df,["celly 2"])

In [123]:
print(df["celly 3"].unique())

<StringArray>
[ '25\n                      Yaşında',  '35\n                      Yaşında',
   '2\n                      Yaşında',  '27\n                      Yaşında',
  '15\n                      Yaşında',  '10\n                      Yaşında',
  '20\n                      Yaşında',  '30\n                      Yaşında',
  '16\n                      Yaşında',  '11\n                      Yaşında',
  '31\n                      Yaşında',                         'Sıfır Bina',
   '5\n                      Yaşında',  '26\n                      Yaşında',
  '12\n                      Yaşında',   '4\n                      Yaşında',
   '6\n                      Yaşında',  '22\n                      Yaşında',
  '23\n                      Yaşında',  '29\n                      Yaşında',
   '3\n                      Yaşında',   '8\n                      Yaşında',
  '33\n                      Yaşında',  '50\n                      Yaşında',
   '7\n                      Yaşında',  '18\n                      Yaşında',
  '32\n                      Yaşında',  '28\n                      Yaşında',
  '14\n                      Yaşında',  '40\n                      Yaşında',
   '9\n                      Yaşında',  '21\n                      Yaşında',
  '45\n                      Yaşında',  '38\n                      Yaşında',
  '19\n                      Yaşında',  '24\n                      Yaşında',
  '17\n                      Yaşında',   '1\n                      Yaşında',
  '36\n                      Yaşında',  '34\n                      Yaşında',
  '13\n                      Yaşında',  '42\n                      Yaşında',
  '44\n                      Yaşında',  '43\n                      Yaşında',
  '37\n                      Yaşında',  '55\n                      Yaşında',
  '47\n                      Yaşında',  '39\n                      Yaşında',
  '49\n                      Yaşında',  '52\n                      Yaşında',
 '300\n                      Yaşında', '199\n                      Yaşında',
  '48\n                      Yaşında',  '60\n                      Yaşında',
  '61\n                      Yaşında', '600\n                      Yaşında',
 '100\n                      Yaşında']
Length: 57, dtype: str

In [128]:
df["celly 3"] = df["celly 3"].apply(lambda x : x.replace('Sıfır Bina','0'))

celly 3'de 'Sıfır Bina' şeklinde string ifadeler var bunları '0' ile değiştiriyoruz

In [136]:
df["age"] = df["celly 3"].apply(lambda x : x.split("\n")[0]).astype(int)

In [137]:
print((df["age"].unique()))

[ 25  35   2  27  15  10  20  30  16  11  31   0   5  26  12   4   6  22
  23  29   3   8  33  50   7  18  32  28  14  40   9  21  45  38  19  24
  17   1  36  34  13  42  44  43  37  55  47  39  49  52 300 199  48  60
  61 600 100]

In [140]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   list-view-price  8136 non-null   object
 1   celly 3          8136 non-null   str
 2   celly 4          6858 non-null   str
 3   city             8136 non-null   object
 4   district         8136 non-null   object
 5   neighborhood     8136 non-null   str
 6   room             8136 non-null   int64
 7   living_room      8136 non-null   int64
 8   area             8136 non-null   int64
 9   age              8136 non-null   int64
dtypes: int64(4), object(3), str(3)
memory usage: 635.8+ KB
None

In [141]:
drop_columns(df,['celly 3'])

In [142]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   list-view-price  8136 non-null   object
 1   celly 4          6858 non-null   str
 2   city             8136 non-null   object
 3   district         8136 non-null   object
 4   neighborhood     8136 non-null   str
 5   room             8136 non-null   int64
 6   living_room      8136 non-null   int64
 7   area             8136 non-null   int64
 8   age              8136 non-null   int64
dtypes: int64(4), object(3), str(2)
memory usage: 572.2+ KB

In [143]:
print(df["celly 4"].unique())

<StringArray>
[   'Yüksek Giriş',          '3. Kat',         'Ara Kat',          '4. Kat',
          '2. Kat',           'Zemin',               nan,        'Tripleks',
      'Villa Katı',      'Bahçe Katı',          '1. Kat',          '8. Kat',
          '6. Kat',      'Giriş Katı',          '5. Kat',          '7. Kat',
     '21 ve üzeri',      'En Üst Kat',      'Teras Katı',         '13. Kat',
           'Kot 1',          '9. Kat',       'Çatı Katı',         '10. Kat',
         '12. Kat',           'Kot 2',         '15. Kat', 'Bodrum ve Zemin',
         '11. Kat',           'Kot 3',         '18. Kat',         '20. Kat',
     'Yarı Bodrum',         '14. Kat',         '16. Kat',         '17. Kat',
        'Asma Kat',          'Bodrum',         '19. Kat']
Length: 39, dtype: str